[build]
  publish = "public" # Or the directory where your Hugo site generates the static files
  command = "hugo --baseURL https://smallzoodev.netlify.app/" # This is the default build command for Hugo

[build.environment]
  HUGO_VERSION = "0.123.8"