#!/bin/bash

# 디버깅을 위한 로그 출력
echo "Starting pre-commit hook..."

# 스테이징된 마크다운 파일들을 찾습니다
files=$(git diff --cached --name-only --diff-filter=ACM | grep '\.md$')

# 파일 목록 출력
echo "Found files: $files"

for file in $files; do
    echo "Processing file: $file"
    
    current_time=$(date '+%Y-%m-%d %H:%M:%S +0900')
    echo "Current time: $current_time"
    
    tmp_file=$(mktemp)
    cat "$file" > "$tmp_file"
    
    awk -v time="$current_time" '
    /^lastmod:/ {print "lastmod: " time; next}
    {print}
    ' "$tmp_file" > "$file"
    
    rm "$tmp_file"
    
    git add "$file"
    echo "Updated and staged: $file"
done

echo "Pre-commit hook completed"
exit 0 